### ISSUE TITLE
Open code inside the IDE or inside the editor?

### ISSUE THREAD

**Issue by graham83** [adospace/chatgpt-vs-tool#1]
Great initiative - What is your intent here? A separate ChatGPT panel (I think extensions like this already exist) or prompt engine directly in the editor, similar to how snippets work?

![image](https://user-images.githubusercontent.com/5820894/223287585-892c8ca0-dd10-4ecd-86aa-5d13079424c2.png)

E.g. As POC:
1. Press shortcut key
2. Enter prompt
3. Review response from ChatGPT
4. Press 'Enter' to insert ChatGPT snippet OR
5. Modify prompt to regenerate snippet using same chatgpt thread

**Comment by adospace** [comment]
Well, initially it was my journey in the creation of extensions using the new extensibility model for Visual Studio. 

My idea is to have a separate tool window like it's now that allows you to chat to GPT asking different kinds of questions even not strictly related to your current code. For example, I guess, you could ask it to revisit the current function in order to optimize its performance or to check for possible errors but at the same time have a conversation about how to implement Okta authentication for your ASP.NET core server or ask which is that particular attribute to use to augment the ef core model, etc

Of course, nothing compared to a fully integrated service like copilot but even not so expensive.

I liked to present results fully formatted and easy to read and this is something I didn't find in existing extensions.

I'm going to use it on daily development to see how effective is and which features I will need.

BTW thanks for your interest
